/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoviraj.gui;

import autoviraj.dao.InvoiceDao;
import autoviraj.models.Customer;
import autoviraj.models.Invoice;
import autoviraj.models.InvoiceItem;
import autoviraj.models.InvoiceService;
import autoviraj.models.Item;
import autoviraj.models.ItemCodeGenerator;
import autoviraj.models.Service;
import autoviraj.models.Vehicle;
import autoviraj.services.PrintInvoice;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author anjanag
 */
public class InvoiceFrame extends javax.swing.JFrame {

    static Map<String, Item> itemMap;
    static Map<String, Service> serviceMap;
    double grandTotal = 0;
    double serviceTotal = 0;
    double itemTotal = 0;
    double serviceDiscountA = 0;
    double itemDiscount = 0;

    /**
     * Creates new form InvoiceFrame
     */
    public InvoiceFrame() {
        initComponents();
        try {
            ItemCodeGenerator it = new ItemCodeGenerator();
            it.createServiceMap();
            it.createItemMap();
            itemMap = it.getItemMap();
            serviceMap = it.getServiceMap();
        } catch (IOException e) {
            e.printStackTrace();
        }
        invoiceNoTxt.setText((InvoiceDao.getLastInvoiceNo()+1) + "");
        jobNoTxt.setText("1");
        datePicker.setDate(new Date());
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                String ObjButtons[] = {"Yes", "No"};
                int PromptResult = JOptionPane.showOptionDialog(null, "Are you sure you want to exit?", "AutoViraj", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, ObjButtons, ObjButtons[1]);
                if (PromptResult == JOptionPane.YES_OPTION) {
                    InvoiceFrame.this.dispose();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        invoiceNoLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        invoiceNoTxt = new javax.swing.JTextField();
        vehicleNoTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vehicleTypeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        serviceTypeTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jobNoTxt = new javax.swing.JTextField();
        customerCodeTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        customerNameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newCustBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        customerTelTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTabel = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        addBtn = new javax.swing.JButton();
        prviewBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        serviceTotalTxt = new javax.swing.JTextField();
        matTotalTxt = new javax.swing.JTextField();
        grandTotalTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        serviceDiscountAmnt = new javax.swing.JTextField();
        matDiscountAmnt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        serviceDiscount = new javax.swing.JTextField();
        matDiscount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane2 = new javax.swing.JScrollPane();
        serviceTabel = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        odometerTxt = new javax.swing.JTextField();
        nextServiceTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 771));

        invoiceNoLbl.setText(" Invoice Number : ");

        dateLbl.setText(" Date :");

        invoiceNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceNoTxtActionPerformed(evt);
            }
        });

        jLabel1.setText(" Vehicle Number : ");

        jLabel4.setText(" Vehicle Type : ");

        jLabel2.setText("Service Type :");

        jLabel3.setText("Job No : ");

        jLabel5.setText(" Customer Code : ");

        jLabel6.setText(" Customer Name : ");

        newCustBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new customer.png"))); // NOI18N
        newCustBtn.setText("New Customer");

        jLabel7.setText(" Telephone No :");

        itemTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Item", "Rate", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        itemTabel.setColumnSelectionAllowed(true);
        itemTabel.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                itemTabelInputMethodTextChanged(evt);
            }
        });
        itemTabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemTabelKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(itemTabel);
        itemTabel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (itemTabel.getColumnModel().getColumnCount() > 0) {
            itemTabel.getColumnModel().getColumn(1).setPreferredWidth(750);
            itemTabel.getColumnModel().getColumn(2).setResizable(false);
        }

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        prviewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/preview.png"))); // NOI18N
        prviewBtn.setText("Preview");
        prviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prviewBtnActionPerformed(evt);
            }
        });

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        delBtn.setText("Delete");

        jLabel8.setText("Service Total  :");

        jLabel9.setText("Material Total :");

        jLabel10.setText("Grand Total    :");

        jLabel11.setText("Amount :");

        jLabel12.setText("Amount :");

        serviceDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceDiscountActionPerformed(evt);
            }
        });

        matDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matDiscountActionPerformed(evt);
            }
        });

        jLabel13.setText("Discount % :");

        jLabel14.setText("Discount % :");

        serviceTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Service", "Rate", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        serviceTabel.setColumnSelectionAllowed(true);
        serviceTabel.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                serviceTabelInputMethodTextChanged(evt);
            }
        });
        serviceTabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serviceTabelKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(serviceTabel);
        serviceTabel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (serviceTabel.getColumnModel().getColumnCount() > 0) {
            serviceTabel.getColumnModel().getColumn(1).setPreferredWidth(750);
        }

        jLabel15.setText("Next service :");

        jLabel16.setText("Odometer    :");

        odometerTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odometerTxtActionPerformed(evt);
            }
        });

        nextServiceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextServiceTxtActionPerformed(evt);
            }
        });

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh.png"))); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(invoiceNoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(invoiceNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(prviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(odometerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(nextServiceTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(serviceDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(matDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(serviceDiscountAmnt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matDiscountAmnt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(matTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(grandTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(serviceTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(vehicleNoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(vehicleTypeTxt))
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel2)
                                        .addGap(32, 32, 32)
                                        .addComponent(serviceTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jobNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(customerTelTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(customerCodeTxt))
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(customerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(newCustBtn)
                                        .addGap(14, 14, 14))))
                            .addComponent(jScrollPane2))))
                .addGap(2, 2, 2))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invoiceNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(serviceTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jobNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(customerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(newCustBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(customerTelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serviceTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(serviceDiscountAmnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(serviceDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(4, 4, 4)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(matDiscountAmnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(matDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grandTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(odometerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(4, 4, 4)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextServiceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceNoTxtActionPerformed

    private void itemTabelInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_itemTabelInputMethodTextChanged

    }//GEN-LAST:event_itemTabelInputMethodTextChanged

    private void itemTabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemTabelKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (itemTabel.getSelectedColumn() == 0) {
                String code = itemTabel.getModel().getValueAt(itemTabel.getSelectedRow(), 0).toString();
                if (itemMap.containsKey(code)) {
                    itemTabel.getModel().setValueAt(itemMap.get(code).getName(), itemTabel.getSelectedRow(), 1);
                    itemTabel.getModel().setValueAt(itemMap.get(code).getPrice(), itemTabel.getSelectedRow(), 2);
                    itemTabel.getModel().setValueAt(1, itemTabel.getSelectedRow(), 3);
                    itemTabel.getModel().setValueAt(1 * itemMap.get(code).getPrice(), itemTabel.getSelectedRow(), 4);
                }
                if (itemTabel.getSelectedRow() + 1 == itemTabel.getRowCount()) {
                    DefaultTableModel defaultTableModel = (DefaultTableModel) itemTabel.getModel();
                    defaultTableModel.addRow(new Object[]{"", "", "", ""});
                }
            }
            itemTotal = 0;
            for (int i = 0; i < itemTabel.getRowCount(); i++) {
                double rowTotal = 0;
                try {
                    rowTotal = Double.parseDouble(itemTabel.getModel().getValueAt(i, 2).toString()) * Double.parseDouble(itemTabel.getModel().getValueAt(i, 3).toString());
                    itemTotal += rowTotal;
                } catch (Exception e) {
                }
                itemTabel.getModel().setValueAt(rowTotal, i, 4);
            }
            matTotalTxt.setText((itemTotal - itemTotal * itemDiscount) + "");
            matDiscountAmnt.setText((itemDiscount) * itemTotal + "");
            double serviceFinal = 0;
            double itemFinal = 0;
            try {
                serviceFinal = Double.parseDouble(serviceTotalTxt.getText());
            } catch (Exception e) {
            }
            try {
                itemFinal = Double.parseDouble(matTotalTxt.getText());
            } catch (Exception e) {
            }
            grandTotalTxt.setText(serviceFinal + itemFinal + "");
            grandTotal = serviceFinal+itemFinal;
        }
    }//GEN-LAST:event_itemTabelKeyReleased

    private void serviceTabelInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_serviceTabelInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceTabelInputMethodTextChanged

    private void serviceTabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serviceTabelKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (serviceTabel.getSelectedColumn() == 0) {
                String code = serviceTabel.getModel().getValueAt(serviceTabel.getSelectedRow(), 0).toString();
                if (serviceMap.containsKey(code)) {
                    serviceTabel.getModel().setValueAt(serviceMap.get(code).getName(), serviceTabel.getSelectedRow(), 1);
                    serviceTabel.getModel().setValueAt(serviceMap.get(code).getPrice(), serviceTabel.getSelectedRow(), 2);
                    serviceTabel.getModel().setValueAt(1, serviceTabel.getSelectedRow(), 3);
                    serviceTabel.getModel().setValueAt(1 * serviceMap.get(code).getPrice(), serviceTabel.getSelectedRow(), 4);
                }
                if (serviceTabel.getSelectedRow() + 1 == serviceTabel.getRowCount()) {
                    DefaultTableModel defaultTableModel = (DefaultTableModel) serviceTabel.getModel();
                    defaultTableModel.addRow(new Object[]{"", ""});
                }
            }
            serviceTotal = 0;
            for (int i = 0; i < serviceTabel.getRowCount(); i++) {
                double rowTotal = 0;
                try {
                    rowTotal = Double.parseDouble(serviceTabel.getModel().getValueAt(i, 2).toString()) * Double.parseDouble(serviceTabel.getModel().getValueAt(i, 3).toString());
                    serviceTotal += rowTotal;
                } catch (Exception e) {
                }
                serviceTabel.getModel().setValueAt(rowTotal, i, 4);
            }
            serviceTotalTxt.setText((serviceTotal - serviceTotal * serviceDiscountA) + "");
            serviceDiscountAmnt.setText(serviceDiscountA * serviceTotal + "");
            double serviceFinal = 0;
            double itemFinal = 0;
            try {
                serviceFinal = Double.parseDouble(serviceTotalTxt.getText());
            } catch (Exception e) {
            }
            try {
                itemFinal = Double.parseDouble(matTotalTxt.getText());
            } catch (Exception e) {
            }
            grandTotalTxt.setText(serviceFinal + itemFinal + "");
            grandTotal = serviceFinal+itemFinal;
        }
    }//GEN-LAST:event_serviceTabelKeyReleased

    private void serviceDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceDiscountActionPerformed
        double discount = 0.0;
        try {
            discount = Double.parseDouble(serviceDiscount.getText());
            serviceDiscountA = discount / 100;
            serviceDiscountAmnt.setText((discount / 100) * serviceTotal + "");
            serviceTotalTxt.setText(serviceTotal - serviceDiscountA * serviceTotal + "");
            double serviceFinal = 0;
            double itemFinal = 0;
            try {
                serviceFinal = Double.parseDouble(serviceTotalTxt.getText());
            } catch (Exception e) {
            }
            try {
                itemFinal = Double.parseDouble(matTotalTxt.getText());
            } catch (Exception e) {
            }
            grandTotalTxt.setText(serviceFinal + itemFinal + "");
            grandTotal = serviceFinal+itemFinal;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_serviceDiscountActionPerformed

    private void matDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matDiscountActionPerformed
        double discount = 0.0;
        try {
            discount = Double.parseDouble(matDiscount.getText());
            itemDiscount = discount / 100;
            matDiscountAmnt.setText((discount / 100) * itemTotal + "");
            matTotalTxt.setText(itemTotal - itemDiscount * itemTotal + "");
            double serviceFinal = 0;
            double itemFinal = 0;
            try {
                serviceFinal = Double.parseDouble(serviceTotalTxt.getText());
            } catch (Exception e) {
            }
            try {
                itemFinal = Double.parseDouble(matTotalTxt.getText());
            } catch (Exception e) {
            }
            grandTotalTxt.setText(serviceFinal + itemFinal + "");
            grandTotal = serviceFinal+itemFinal;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_matDiscountActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        Customer c = new Customer();
        c.setName(customerNameTxt.getText());
        c.setTel(customerTelTxt.getText());
        c.setAddress("No-address");

        Vehicle v = new Vehicle();
        v.setRegNo(vehicleNoTxt.getText());
        v.setOdometer(odometerTxt.getSelectedText());
        v.setModel(vehicleTypeTxt.getText());
        v.setType("No-Type");

        ArrayList<InvoiceItem> itemList = new ArrayList<>();
        ArrayList<InvoiceService> serviceList = new ArrayList<>();

        for (int i = 0; i < itemTabel.getModel().getRowCount(); i++) {
            if (itemTabel.getModel().getValueAt(i, 0) != null && itemTabel.getModel().getValueAt(i, 0).toString().trim() != "") {
                InvoiceItem invoiceItem = new InvoiceItem();
                invoiceItem.setItemId(itemTabel.getModel().getValueAt(i, 0) + "");
                invoiceItem.setName(itemTabel.getModel().getValueAt(i, 1) + "");
                invoiceItem.setUnitPrice(Double.parseDouble(itemTabel.getModel().getValueAt(i, 2).toString()));
                invoiceItem.setUnits(Double.parseDouble(itemTabel.getModel().getValueAt(i, 3).toString()));
                invoiceItem.setUnitName(" Nos");
                itemList.add(invoiceItem);
            }
        }

        for (int i = 0; i < serviceTabel.getModel().getRowCount(); i++) {
            if (serviceTabel.getModel().getValueAt(i, 0) != null && serviceTabel.getModel().getValueAt(i, 0).toString().trim() != "") {
                InvoiceService invoiceService = new InvoiceService();
                invoiceService.setServiceId(serviceTabel.getModel().getValueAt(i, 0) + "");
                invoiceService.setName(serviceTabel.getModel().getValueAt(i, 1) + "");
                invoiceService.setUnitPrice(Double.parseDouble(serviceTabel.getModel().getValueAt(i, 2).toString()));
                invoiceService.setUnits(Double.parseDouble(serviceTabel.getModel().getValueAt(i, 3).toString()));
                invoiceService.setUnitName(" Nos");
                serviceList.add(invoiceService);
            }
        }

        Invoice i = new Invoice();
        i.setInvoiceItems(itemList);
        i.setInvoiceServices(serviceList);
        i.setSubtotal(grandTotal + serviceDiscountA + itemDiscount);
        i.setDiscount(itemDiscount);
        i.setNetTotal(grandTotal);
        i.setDate(datePicker.getDate());

        i.setCustomer(c);
        i.setVehicle(v);

        try {
            PrintInvoice.printInvoice(i);
        } catch (Exception e) {
            System.out.println(e);
        }
        
        if (InvoiceDao.saveInvoice(i)) {
            URL f = getClass().getResource("/resources/invoice.pdf");
            SwingController controller = new SwingController();
            SwingViewBuilder factory = new SwingViewBuilder(controller);
            JPanel viewerComponentPanel = factory.buildViewerPanel();
            controller.getDocumentViewController().setAnnotationCallback(new org.icepdf.ri.common.MyAnnotationCallback(controller.getDocumentViewController()));
            JFrame applicationFrame = new JFrame();//applicationFrame.getContentPane().add(viewerComponentPanel);
            applicationFrame.add(viewerComponentPanel);
            controller.openDocument(f);
            applicationFrame.pack();
            applicationFrame.setVisible(true);
            applicationFrame.setLocationRelativeTo(null);
            applicationFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            applicationFrame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent we) {
                    applicationFrame.dispose();
                }
            });
        } else {
            JOptionPane.showMessageDialog(null, "Error occured!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void odometerTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odometerTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odometerTxtActionPerformed

    private void nextServiceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextServiceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextServiceTxtActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (true) {
            JOptionPane.showMessageDialog(null, "Invoice saved successfully!", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Error occured!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to reset fields?", "", JOptionPane.YES_NO_CANCEL_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            this.dispose();
            InvoiceFrame ifr = new InvoiceFrame();
            ifr.setVisible(true);
            ifr.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    private void prviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prviewBtnActionPerformed
        URL f = getClass().getResource("/resources/invoice.pdf");
        SwingController controller = new SwingController();
        SwingViewBuilder factory = new SwingViewBuilder(controller);
        JPanel viewerComponentPanel = factory.buildViewerPanel();
        controller.getDocumentViewController().setAnnotationCallback(new org.icepdf.ri.common.MyAnnotationCallback(controller.getDocumentViewController()));
        JFrame applicationFrame = new JFrame();//applicationFrame.getContentPane().add(viewerComponentPanel);
        applicationFrame.add(viewerComponentPanel);
        controller.openDocument(f);
        applicationFrame.pack();
        applicationFrame.setVisible(true);
        applicationFrame.setLocationRelativeTo(null);
        applicationFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        applicationFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                applicationFrame.dispose();
            }
        });
    }//GEN-LAST:event_prviewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvoiceFrame ifr = new InvoiceFrame();
                ifr.setVisible(true);
                ifr.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField customerCodeTxt;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JTextField customerTelTxt;
    private javax.swing.JLabel dateLbl;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField grandTotalTxt;
    private javax.swing.JLabel invoiceNoLbl;
    private javax.swing.JTextField invoiceNoTxt;
    private javax.swing.JTable itemTabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jobNoTxt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField matDiscount;
    private javax.swing.JTextField matDiscountAmnt;
    private javax.swing.JTextField matTotalTxt;
    private javax.swing.JButton newCustBtn;
    private javax.swing.JTextField nextServiceTxt;
    private javax.swing.JTextField odometerTxt;
    private javax.swing.JButton prviewBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField serviceDiscount;
    private javax.swing.JTextField serviceDiscountAmnt;
    private javax.swing.JTable serviceTabel;
    private javax.swing.JTextField serviceTotalTxt;
    private javax.swing.JTextField serviceTypeTxt;
    private javax.swing.JTextField vehicleNoTxt;
    private javax.swing.JTextField vehicleTypeTxt;
    // End of variables declaration//GEN-END:variables
}
