/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoviraj.gui;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author anjanag
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                String ObjButtons[] = {"Yes", "No"};
                int PromptResult = JOptionPane.showOptionDialog(null, "Are you sure you want to close the program?", "AutoViraj", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, ObjButtons, ObjButtons[1]);
                if (PromptResult == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        runMenu = new javax.swing.JMenu();
        invoiceMenu = new javax.swing.JMenuItem();
        historyMenuItem = new javax.swing.JMenuItem();
        viewMenuItme = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/papers.co-ad74-bmw-car-black-light-23-wallpaper.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        runMenu.setText("Run");

        invoiceMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        invoiceMenu.setText("Create Invoice");
        invoiceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceMenuActionPerformed(evt);
            }
        });
        runMenu.add(invoiceMenu);

        historyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        historyMenuItem.setText("View History");
        historyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyMenuItemActionPerformed(evt);
            }
        });
        runMenu.add(historyMenuItem);

        viewMenuItme.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        viewMenuItme.setText("View Inventory");
        viewMenuItme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMenuItmeActionPerformed(evt);
            }
        });
        runMenu.add(viewMenuItme);

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("View Customers");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        runMenu.add(jCheckBoxMenuItem1);

        jMenuBar1.add(runMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceMenuActionPerformed

        if (ifr != null) {
            String ObjButtons[] = {"Yes", "No"};
            int PromptResult = JOptionPane.showOptionDialog(null, "Are you sure you want to create new invoice?", "Burner", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, ObjButtons, ObjButtons[1]);
            if (PromptResult == JOptionPane.YES_OPTION) {
                ifr.dispose();
                ifr = new InvoiceFrame();
                ifr.setVisible(true);
                ifr.setLocationRelativeTo(null);
            } else {
                vfr.toFront();
                hfr.toFront();
                ifr.toFront();
            }

        } else {
            ifr = new InvoiceFrame();
            ifr.setVisible(true);
            ifr.setLocationRelativeTo(null);
        }
        if(vfr != null)
            vfr.toFront();
        if(hfr!=null)
            hfr.toFront();
        if(cfr!=null)
            cfr.toFront();
        ifr.toFront();
    }//GEN-LAST:event_invoiceMenuActionPerformed

    private void viewMenuItmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMenuItmeActionPerformed
        if (vfr != null) {
            vfr.dispose();
        }
        vfr = new ViewForm();
        vfr.setVisible(true);
        vfr.setLocationRelativeTo(null);
        if(ifr!=null)
            ifr.toFront();
        if(hfr!=null)
            hfr.toFront();
        if(cfr!=null)
            cfr.toFront();
        vfr.toFront();
    }//GEN-LAST:event_viewMenuItmeActionPerformed

    private void historyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyMenuItemActionPerformed
        if (hfr != null) {
            hfr.dispose();
        }
        hfr = new HistoryForm();
        hfr.setVisible(true);
        hfr.setLocationRelativeTo(null);
        if(vfr != null)
            vfr.toFront();
        if(ifr!=null)
            ifr.toFront();
        if(cfr!=null)
            cfr.toFront();
        hfr.toFront();
    }//GEN-LAST:event_historyMenuItemActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(vfr != null)
            vfr.toFront();
        if(ifr!=null)
            ifr.toFront();
        if(hfr!=null)
            hfr.toFront();
        if(cfr!=null)
            cfr.toFront();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        if (cfr != null) {
            cfr.dispose();
        }
        cfr = new CustomerForm();
        cfr.setVisible(true);
        cfr.setLocationRelativeTo(null);
        if(vfr != null)
            vfr.toFront();
        if(ifr!=null)
            ifr.toFront();
        if(hfr!=null)
            hfr.toFront();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    InvoiceFrame ifr;
    HistoryForm hfr;
    ViewForm vfr;
    CustomerForm cfr;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem historyMenuItem;
    private javax.swing.JMenuItem invoiceMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu runMenu;
    private javax.swing.JMenuItem viewMenuItme;
    // End of variables declaration//GEN-END:variables
}
